// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://fzdhkkqagmrwaopeednz.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImZ6ZGhra3FhZ21yd2FvcGVlZG56Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTczNzMzNjMsImV4cCI6MjA3Mjk0OTM2M30.EWEKqwvR5uxw3D_EJRCTzWxLMBatjpeIfrdvlGLXZD4";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});